/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HallRouteImport } from './routes/hall'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as WrapRouteImport } from './routes/wrap'
import { Route as FranchiseNameRouteImport } from './routes/franchise.$name'
import { Route as GameIdRouteImport } from './routes/game.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HallRoute = HallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const WrapRoute = WrapRouteImport.update({
  id: '/wrap',
  path: '/wrap',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseNameRoute = FranchiseNameRouteImport.update({
  id: '/franchise/$name',
  path: '/franchise/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hall': typeof HallRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/store': typeof StoreRoute
  '/timeline': typeof TimelineRoute
  '/upcoming': typeof UpcomingRoute
  '/wrap': typeof WrapRoute
  '/franchise/$name': typeof FranchiseNameRoute
  '/game/$id': typeof GameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hall': typeof HallRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/store': typeof StoreRoute
  '/timeline': typeof TimelineRoute
  '/upcoming': typeof UpcomingRoute
  '/wrap': typeof WrapRoute
  '/franchise/$name': typeof FranchiseNameRoute
  '/game/$id': typeof GameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hall': typeof HallRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/store': typeof StoreRoute
  '/timeline': typeof TimelineRoute
  '/upcoming': typeof UpcomingRoute
  '/wrap': typeof WrapRoute
  '/franchise/$name': typeof FranchiseNameRoute
  '/game/$id': typeof GameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hall'
    | '/home'
    | '/library'
    | '/news'
    | '/profile'
    | '/search'
    | '/settings'
    | '/stats'
    | '/store'
    | '/timeline'
    | '/upcoming'
    | '/wrap'
    | '/franchise/$name'
    | '/game/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hall'
    | '/home'
    | '/library'
    | '/news'
    | '/profile'
    | '/search'
    | '/settings'
    | '/stats'
    | '/store'
    | '/timeline'
    | '/upcoming'
    | '/wrap'
    | '/franchise/$name'
    | '/game/$id'
  id:
    | '__root__'
    | '/'
    | '/hall'
    | '/home'
    | '/library'
    | '/news'
    | '/profile'
    | '/search'
    | '/settings'
    | '/stats'
    | '/store'
    | '/timeline'
    | '/upcoming'
    | '/wrap'
    | '/franchise/$name'
    | '/game/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HallRoute: typeof HallRoute
  HomeRoute: typeof HomeRoute
  LibraryRoute: typeof LibraryRoute
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  StoreRoute: typeof StoreRoute
  TimelineRoute: typeof TimelineRoute
  UpcomingRoute: typeof UpcomingRoute
  WrapRoute: typeof WrapRoute
  FranchiseNameRoute: typeof FranchiseNameRoute
  GameIdRoute: typeof GameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall': {
      id: '/hall'
      path: '/hall'
      fullPath: '/hall'
      preLoaderRoute: typeof HallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrap': {
      id: '/wrap'
      path: '/wrap'
      fullPath: '/wrap'
      preLoaderRoute: typeof WrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise/$name': {
      id: '/franchise/$name'
      path: '/franchise/$name'
      fullPath: '/franchise/$name'
      preLoaderRoute: typeof FranchiseNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HallRoute: HallRoute,
  HomeRoute: HomeRoute,
  LibraryRoute: LibraryRoute,
  NewsRoute: NewsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  StoreRoute: StoreRoute,
  TimelineRoute: TimelineRoute,
  UpcomingRoute: UpcomingRoute,
  WrapRoute: WrapRoute,
  FranchiseNameRoute: FranchiseNameRoute,
  GameIdRoute: GameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
